config/routes.rb
Rails.application.routes.draw do

  resources :memory
  
  root 'home#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/experience.rb
class Experience < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/memory_controller.rb
class MemoryController < ApplicationController
  def new
    @memory = Experience.new
  end

  def edit
  end

  def create
  end

  def remove
  end

  def update
  end

  def delete
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/memory_helper.rb
module MemoryHelper
end

app/views/home/_actions.html.erb
<% content_for :actions do %>
    <li><%= link_to ('<i class="material-icons">add</i>').html_safe, new_memory_path, class: 'btn-floating blue' %></li>
<% end %>

app/views/home/index.html.erb
<%= render 'actions' %>
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Memory</title>
    <%= csrf_meta_tags %>

    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <div class="nav-wrapper blue">
        <a href="<%= root_path %>" class="brand-logo black-text" style="margin-left: 1em;"><i class="material-icons">home</i></a>
        <ul class="right hide-on-med-and-down">
          <li>
            <%# render partial: 'users/shared/login_items' %>
          </li>
        </ul>
      </div>
    </nav>
    <%= yield %>
    <div class="fixed-action-btn">
    <a class="btn-floating btn-large red">
      <i class="large material-icons">menu</i>
    </a>
    <ul>
      <%= yield :actions %>
    </ul>
  </div>
  </body>
</html>

app/views/memory/_actions.html.erb
<% content_for :actions do %>
    <li><%= link_to ('<i class="material-icons">add</i>').html_safe, new_memory_path, class: 'btn-floating blue' %></li>
<% end %>

app/views/memory/_form.html.erb
<div class="container">
  <div class="row">
    <%= form_for @memory, html: {:class => 'col s12'} do |f| %>
      <div class="row">
        <% if @memory.errors.any? %>
            <div id="error_explanation">
              <h2>
                <%= pluralize(@memory.errors.count, 'error') %> prohibited
                this card from being saved:
              </h2>
              <ul>
                <% @memory.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <div class="input-field col s12">
          <%= f.text_field :title, class: 'validate' %>
          <%= f.label :title %>
        </div>

        <div class="input-field col s12">
          <%= f.text_area :description, class: 'materialize-textarea' %>
          <%= f.label :description %>
        </div>

        <div class="input-field col s6">
          <% if current_user.role == 1 %>
          <%= collection_select :card, :source, User.where.not(role: 2), :id, :name %>
          <% else %>
          <%= collection_select :card, :source, User.where(id: current_user.id), :id, :name %>
          <% end %>
          <%= f.label :source %>
        </div>
        <div class="input-field col s6">
          <%= collection_select :card, :era, Era.all, :id, :name, prompt: true %>
          <%= f.label :era %>
        </div>

        <div class="file-field input-field col s12">
          <div class="btn">
            <span>Picture</span>
            <!--<input type="file">-->
            <%= f.file_field :media %>
          </div>
          <div class="file-path-wrapper">
            <input class="file-path validate" type="text">
          </div>
        </div>

        <%= f.submit class: 'btn waves-effect waves-light' %>
      </div>
    <% end %>
  </div>
</div>

app/views/memory/edit.html.erb
<%= render 'form' %>

app/views/memory/new.html.erb
<%= render 'form' %>